baseurl: "/rinchen123"

collections_dir: content

collections:
  stories:
    output: true
    permalink: /stories/:name/

defaults:
  - scope:
      path: ""
      type: stories
    values:
      layout: story
